version: 2.1

orbs:
  github-cli: circleci/github-cli@1.0.4

parameters:
  do-release:
    type: boolean
    default: false

jobs:
  ci:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout

      - restore_cache:
          keys:
            - node-v1-{{ checksum "package-lock.json" }}

      - run: |
          git config user.email "$EMAIL"
          git config user.name "$GIT_USERNAME"

      - run:
          name: Install dependencies
          command: npm ci

      - run:
          name: Electron Postinstall
          command: npm run electron:postinstall

      - save_cache:
          key: node-v1-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm

      - run:
          name: Run linter
          command: npm run lint

      - run:
          name: Build Electron App
          command: npm run electron:build

      - when:
          condition:
            equal: [true, << pipeline.parameters.do-release >>]
          steps:
            - run: git tag -l | grep \- | xargs git tag -d
            - run:
                name: Version and Release Production
                command: |
                  npm run release -- --message "chore(release): %s [ci skip]"

      - run: git push --follow-tags origin main

      - persist_to_workspace:
          root: dist
          paths: .

workflows:
  version: 2
  ci:
    jobs:
      - ci:
          filters:
            branches:
              only:
                - main
